steps:
    #builds the docker image
    - name: 'gcr.io/cloud-builders/docker'
      args: ["build", "-t", "gcr.io/smart-brain-242707/multi-frontend:$SHORT_SHA", "-t", "gcr.io/smart-brain-242707/multi-frontend:latest", './frontend']

    - name: 'gcr.io/cloud-builders/docker'
      args: ["build", "-t", "gcr.io/smart-brain-242707/multi-backend:$SHORT_SHA","-t", "gcr.io/smart-brain-242707/multi-backend:latest", './backend']

    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/smart-brain-242707/multi-frontend:$SHORT_SHA"]

    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/smart-brain-242707/multi-frontend:latest"]

    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/smart-brain-242707/multi-backend:$SHORT_SHA"]

    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/smart-brain-242707/multi-backend:latest"]

    - name: 'gcr.io/cloud-builders/gke-deploy:stable'
      args:
        - run
        - --filename=k8s
        - --location=us-central1-a
        - --cluster=smart-brain