version : "3.6"
services:
    backend:
        image: eze09/multi-backend:v1
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: smart-brain-docker
            REDIS_HOST: redis
            REDIS_PORT: '6379'
            REDIS_URI: redis://redis:6379
        volumes:
            - /var/www/node_modules
            - ./backend:/var/www   
    frontend:
        image: eze09/multi-frontend
        volumes:
            - /var/www/node_modules
            - ./frontend:/var/www
    postgres:
        image: eze09/postgres:v1
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: smart-brain-docker
        # Expose the default Postgres port on localhost
    redis:
        image: redis
    nginx:
        restart: always
        depends_on:
            - frontend
            - backend
        ports:
            - '5000:8080'
        build: 
            context: ./nginx
            dockerfile: Dockerfile.dev
# secrets:
#     my_secret:
#         file: ./password.txt


