apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: postgres
    template:
        metadata:
            labels:
                component: postgres
        spec:
            volumes:
                - name: postgres-storage
                  persistentVolumeClaim:
                    claimName: database-persistant-volume-claim
            containers:
                - name: postgres
                  image: eze09/postgres:v1
                  ports:
                    - containerPort: 5432
                  volumeMounts:
                    - name: postgres-storage
                      mountPath: "/var/lib/postgresql/data"
                      subPath: postgres
                  env:
                    - name: POSTGRES_USER
                      value: postgres
                    - name: POSTGRES_DB
                      value: smart-brain-docker
                    - name: POSTGRES_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: pgpassword
                            key:  POSTGRES_PASSWORD
