apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            component: server
    template:
        metadata:
            labels:
                component: server
        spec:
            containers:
                - name: server
                  image: eze09/multi-backend
                  ports:
                    - containerPort: 3001
                  env:
                    - name: POSTGRES_USER
                      value: postgres
                    - name: POSTGRES_HOST
                      value: postgres-clusterip-service
                    - name: POSTGRES_DB
                      value: smart-brain-docker
                    - name: POSTGRES_PORT
                      value: '5432'
                    - name: POSTGRES_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: pgpassword
                            key:  POSTGRES_PASSWORD
                    - name: REDIS_HOST
                      value: redis-clusterip-service
                    - name: REDIS_PORT
                      value: '6379'
                    - name: REDIS_URI
                      value: redis://redis-clusterip-service:6379
