apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            component: server
    template:
        metadata:
            labels:
                component: server
        spec:
            containers:
                - name: server
                  image: eze09/multi-backend
                  ports:
                    - containerPort: 3001
                  env:
                    - name: POSTGRES_URI
                      value: "postgres://postgres-clusterip-service:secret@postgres:5432/smart-brain-docker"
                    - name: REDIS_URI
                      value: "redis://redis-clusterip-service:6379"
