apiVersion: v1
kind: Service
metadata:
    name: server-clusterip-service
spec:
    type: LoadBalancer
    selector:
        component: server
    ports:
        - port: 3001
          targetPort: 3001
